# Generated by Django 5.2.7 on 2025-10-31 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('display_value', models.CharField(blank=True, max_length=100, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variation_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jewelry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewelry_items', to='store.category'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variation_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='store.jewelry')),
                ('variation_options', models.ManyToManyField(related_name='product_variations', to='store.variationoption')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.productvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'jewelry', 'product_variation')},
        ),
        migrations.AddField(
            model_name='variationoption',
            name='variation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.variationtype'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='variation_types',
            field=models.ManyToManyField(blank=True, related_name='jewelry_items', to='store.variationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='variationoption',
            unique_together={('variation_type', 'value')},
        ),
    ]
